/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: sensor_data.proto */

#ifndef PROTOBUF_C_sensor_5fdata_2eproto__INCLUDED
#define PROTOBUF_C_sensor_5fdata_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003003 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _Sensor__SensorData Sensor__SensorData;


/* --- enums --- */


/* --- messages --- */

struct  _Sensor__SensorData
{
  ProtobufCMessage base;
  size_t n_temperature;
  float *temperature;
  size_t n_precipitation;
  float *precipitation;
  size_t n_soil_moisture;
  float *soil_moisture;
  size_t n_wind;
  float *wind;
  float pressure;
  uint32_t light_level;
  protobuf_c_boolean raining;
  uint64_t timestamp;
  char *device_id;
  uint32_t battery_level;
  uint32_t sequence_number;
};
#define SENSOR__SENSOR_DATA__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&sensor__sensor_data__descriptor) \
    , 0,NULL, 0,NULL, 0,NULL, 0,NULL, 0, 0, 0, 0, (char *)protobuf_c_empty_string, 0, 0 }


/* Sensor__SensorData methods */
void   sensor__sensor_data__init
                     (Sensor__SensorData         *message);
size_t sensor__sensor_data__get_packed_size
                     (const Sensor__SensorData   *message);
size_t sensor__sensor_data__pack
                     (const Sensor__SensorData   *message,
                      uint8_t             *out);
size_t sensor__sensor_data__pack_to_buffer
                     (const Sensor__SensorData   *message,
                      ProtobufCBuffer     *buffer);
Sensor__SensorData *
       sensor__sensor_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   sensor__sensor_data__free_unpacked
                     (Sensor__SensorData *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Sensor__SensorData_Closure)
                 (const Sensor__SensorData *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor sensor__sensor_data__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_sensor_5fdata_2eproto__INCLUDED */
