/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: sensor_data.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "sensor_data.pb-c.h"
void   sensor__sensor_data__init
                     (Sensor__SensorData         *message)
{
  static const Sensor__SensorData init_value = SENSOR__SENSOR_DATA__INIT;
  *message = init_value;
}
size_t sensor__sensor_data__get_packed_size
                     (const Sensor__SensorData *message)
{
  assert(message->base.descriptor == &sensor__sensor_data__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sensor__sensor_data__pack
                     (const Sensor__SensorData *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &sensor__sensor_data__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sensor__sensor_data__pack_to_buffer
                     (const Sensor__SensorData *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &sensor__sensor_data__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Sensor__SensorData *
       sensor__sensor_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Sensor__SensorData *)
     protobuf_c_message_unpack (&sensor__sensor_data__descriptor,
                                allocator, len, data);
}
void   sensor__sensor_data__free_unpacked
                     (Sensor__SensorData *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &sensor__sensor_data__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor sensor__sensor_data__field_descriptors[11] =
{
  {
    "temperature",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(Sensor__SensorData, n_temperature),
    offsetof(Sensor__SensorData, temperature),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "precipitation",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(Sensor__SensorData, n_precipitation),
    offsetof(Sensor__SensorData, precipitation),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "soil_moisture",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(Sensor__SensorData, n_soil_moisture),
    offsetof(Sensor__SensorData, soil_moisture),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "wind",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(Sensor__SensorData, n_wind),
    offsetof(Sensor__SensorData, wind),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pressure",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Sensor__SensorData, pressure),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "light_level",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Sensor__SensorData, light_level),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "raining",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Sensor__SensorData, raining),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "timestamp",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Sensor__SensorData, timestamp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "device_id",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Sensor__SensorData, device_id),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "battery_level",
    10,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Sensor__SensorData, battery_level),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sequence_number",
    11,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Sensor__SensorData, sequence_number),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sensor__sensor_data__field_indices_by_name[] = {
  9,   /* field[9] = battery_level */
  8,   /* field[8] = device_id */
  5,   /* field[5] = light_level */
  1,   /* field[1] = precipitation */
  4,   /* field[4] = pressure */
  6,   /* field[6] = raining */
  10,   /* field[10] = sequence_number */
  2,   /* field[2] = soil_moisture */
  0,   /* field[0] = temperature */
  7,   /* field[7] = timestamp */
  3,   /* field[3] = wind */
};
static const ProtobufCIntRange sensor__sensor_data__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 11 }
};
const ProtobufCMessageDescriptor sensor__sensor_data__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "sensor.SensorData",
  "SensorData",
  "Sensor__SensorData",
  "sensor",
  sizeof(Sensor__SensorData),
  11,
  sensor__sensor_data__field_descriptors,
  sensor__sensor_data__field_indices_by_name,
  1,  sensor__sensor_data__number_ranges,
  (ProtobufCMessageInit) sensor__sensor_data__init,
  NULL,NULL,NULL    /* reserved[123] */
};
